"""danh muc, nguyen lieu, canh bao

Revision ID: 0f75367b81aa
Revises: 612a2ac8a3b4
Create Date: 2026-10-01 15:30:14.990134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f75367b81aa'
down_revision: Union[str, Sequence[str], None] = '612a2ac8a3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_code', sa.String(length=32), nullable=False),
    sa.Column('tax_code', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('galvanizers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material_receipts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('steel_grade', sa.String(length=40), nullable=False),
    sa.Column('spec', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_receipts_date'), ['date'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('default_driver', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('customer_tags',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'tag_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.String(length=80), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_plate', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('galvanizer_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_vehicle_plate'), ['vehicle_plate'], unique=False)

    # ### end Alembic commands ###
    # Dữ liệu có sẵn: tạo danh mục khách hàng từ tên khách trên đơn hàng và liên kết đơn → khách.
    op.execute(
        "INSERT INTO customers (name, short_code, tax_code, address, contact_name, phone, note, active, created_at) "
        "SELECT customer, '', '', '', '', '', '', TRUE, MIN(date) FROM orders GROUP BY customer"
    )
    op.execute("UPDATE orders SET customer_id = (SELECT c.id FROM customers c WHERE c.name = orders.customer)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_vehicle_plate'))
        batch_op.drop_column('galvanizer_id')
        batch_op.drop_column('vehicle_plate')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('roles')

    op.drop_table('customer_tags')
    op.drop_table('vehicles')
    op.drop_table('tags')
    with op.batch_alter_table('material_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_receipts_date'))

    op.drop_table('material_receipts')
    op.drop_table('galvanizers')
    op.drop_table('customers')
    # ### end Alembic commands ###
