"""khach hang: dai dien, ngan hang, phan loai

Revision ID: eb80ae755cdf
Revises: 0f75367b81aa
Create Date: 2026-10-03 09:42:58.275556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb80ae755cdf'
down_revision: Union[str, Sequence[str], None] = '0f75367b81aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('representative', sa.String(length=120), server_default='', nullable=False))
        batch_op.add_column(sa.Column('representative_title', sa.String(length=80), server_default='', nullable=False))
        batch_op.add_column(sa.Column('bank_account', sa.String(length=40), server_default='', nullable=False))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=200), server_default='', nullable=False))
        batch_op.add_column(sa.Column('segment', sa.String(length=20), server_default='', nullable=False))
        batch_op.create_index(batch_op.f('ix_customers_segment'), ['segment'], unique=False)

    # ### end Alembic commands ###
    # chuyển dữ liệu: khách đang gắn nhãn "Khách thân thiết" / "Khách lẻ" → phân loại tương ứng
    for tag_name, seg in (("Khách thân thiết", "Thân thiết"), ("Khách lẻ", "Đơn lẻ")):
        op.execute(sa.text(
            "UPDATE customers SET segment = :seg WHERE segment = '' AND id IN ("
            " SELECT ct.customer_id FROM customer_tags ct JOIN tags t ON t.id = ct.tag_id WHERE t.name = :tag)"
        ).bindparams(seg=seg, tag=tag_name))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_segment'))
        batch_op.drop_column('segment')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('bank_account')
        batch_op.drop_column('representative_title')
        batch_op.drop_column('representative')

    # ### end Alembic commands ###
