"""khoi tao schema

Revision ID: 029bdba52f79
Revises: 
Create Date: 2026-10-01 14:48:28.279781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029bdba52f79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('sent_to_kt_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('sign_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('total_qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('total_kg', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('vat_pct', sa.Float(), nullable=False),
    sa.Column('advance_pct', sa.Float(), nullable=False),
    sa.Column('advance_required', sa.Float(), nullable=False),
    sa.Column('advance_received', sa.Float(), nullable=False),
    sa.Column('advance_received_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lsx',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by', sa.String(length=120), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by', sa.String(length=120), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('qty_plan', sa.Float(), nullable=False),
    sa.Column('kg_plan', sa.Float(), nullable=False),
    sa.Column('qty_done', sa.Float(), nullable=False),
    sa.Column('kg_done', sa.Float(), nullable=False),
    sa.Column('ext_to', sa.DateTime(), nullable=True),
    sa.Column('ext_reason', sa.Text(), nullable=True),
    sa.Column('ext_approved_by', sa.String(length=120), nullable=True),
    sa.Column('ext_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lsx_contract_id'), 'lsx', ['contract_id'], unique=False)
    op.create_table('mismatches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('ref_type', sa.String(length=8), nullable=False),
    sa.Column('ref_id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('expected', sa.Float(), nullable=False),
    sa.Column('actual', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('reason_note', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.String(length=120), nullable=False),
    sa.Column('dept', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signed_by', sa.String(length=120), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mismatches_contract_id'), 'mismatches', ['contract_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sub', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('total_kg', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('lsx_id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_contract_id'), 'receipts', ['contract_id'], unique=False)
    op.create_index(op.f('ix_receipts_lsx_id'), 'receipts', ['lsx_id'], unique=False)
    op.create_table('sequences',
    sa.Column('key', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('driver', sa.String(length=120), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=32), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('departed_at', sa.DateTime(), nullable=True),
    sa.Column('fill_deadline', sa.DateTime(), nullable=True),
    sa.Column('kg_required', sa.Float(), nullable=False),
    sa.Column('kg_at_galv', sa.Float(), nullable=True),
    sa.Column('kg_picked', sa.Float(), nullable=True),
    sa.Column('kg_delivered', sa.Float(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('mismatch_id', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('loss_accepted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_contract_id'), 'tasks', ['contract_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dept', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('roles', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('vloss',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ref_type', sa.String(length=8), nullable=False),
    sa.Column('ref_id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.String(length=120), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vloss_contract_id'), 'vloss', ['contract_id'], unique=False)
    op.create_table('weighings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('lsx_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('kg_expected', sa.Float(), nullable=False),
    sa.Column('kg_actual', sa.Float(), nullable=True),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('signer_boc_xep', sa.String(length=120), nullable=False),
    sa.Column('signer_kho', sa.String(length=120), nullable=False),
    sa.Column('signer_lai_xe', sa.String(length=120), nullable=False),
    sa.Column('by', sa.String(length=120), nullable=False),
    sa.Column('mismatch_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('loss_accepted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weighings_contract_id'), 'weighings', ['contract_id'], unique=False)
    op.create_table('lsx_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lsx_id', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lsx_id'], ['lsx.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_table('lsx_logs')
    op.drop_index(op.f('ix_weighings_contract_id'), table_name='weighings')
    op.drop_table('weighings')
    op.drop_index(op.f('ix_vloss_contract_id'), table_name='vloss')
    op.drop_table('vloss')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_contract_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('sequences')
    op.drop_index(op.f('ix_receipts_lsx_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_contract_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_table('orders')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_mismatches_contract_id'), table_name='mismatches')
    op.drop_table('mismatches')
    op.drop_index(op.f('ix_lsx_contract_id'), table_name='lsx')
    op.drop_table('lsx')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
