"""lich su sua, giao lai — bảng field_changes (lịch sử chỉnh sửa từng trường)

Revision ID: 612a2ac8a3b4
Revises: 029bdba52f79
Create Date: 2026-10-01 15:26:36.867830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612a2ac8a3b4'
down_revision: Union[str, Sequence[str], None] = '029bdba52f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(), nullable=True),
    sa.Column('entity_type', sa.String(length=8), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_changes_at'), 'field_changes', ['at'], unique=False)
    op.create_index(op.f('ix_field_changes_entity_id'), 'field_changes', ['entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_changes_entity_id'), table_name='field_changes')
    op.drop_index(op.f('ix_field_changes_at'), table_name='field_changes')
    op.drop_table('field_changes')
    # ### end Alembic commands ###
